# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Implement a randomwalk Metropolis sampler for generating the standard Laplace distribution
#' @description Implement a randomwalk Metropolis sampler for generating the standard Laplace distribution
#' @param sigma variance
#' @param x0 initial value
#' @param N sample size
#' @return a random sample of size \code{N}
#' @examples
#' \dontrun{
#' rw_MetropolisC(1,25,1000)
#' }
#' @export
rw_MetropolisC <- function(sigma, x0, N) {
    .Call('_SC19012_rw_MetropolisC', PACKAGE = 'SC19012', sigma, x0, N)
}

